export const CATALOG: [string, string][] = [
["Bananas","Produce"],["Apples","Produce"],["Avocados","Produce"],["Strawberries","Produce"],["Blueberries","Produce"],["Grapes","Produce"],["Lemons","Produce"],["Limes","Produce"],["Oranges","Produce"],["Romaine lettuce","Produce"],["Spinach","Produce"],["Broccoli","Produce"],["Carrots","Produce"],["Bell peppers","Produce"],["Roma tomatoes","Produce"],["Cucumbers","Produce"],["Yellow onions","Produce"],["Garlic","Produce"],["Russet potatoes","Produce"],["Sweet potatoes","Produce"],["Cilantro","Produce"],["Jalapeños","Produce"],["Mushrooms","Produce"],["Celery","Produce"],["Green onions","Produce"],
["Whole milk","Dairy"],["2% milk","Dairy"],["Oat milk","Dairy"],["Almond milk","Dairy"],["Large eggs","Dairy"],["Salted butter","Dairy"],["Unsalted butter","Dairy"],["Cheddar cheese","Dairy"],["Shredded mozzarella","Dairy"],["Greek yogurt","Dairy"],["Cream cheese","Dairy"],["Sour cream","Dairy"],["Heavy cream","Dairy"],["Cottage cheese","Dairy"],["String cheese","Dairy"],
["Chicken breast","Meat"],["Chicken thighs","Meat"],["Ground beef 80/20","Meat"],["Ground turkey","Meat"],["Ribeye steak","Meat"],["Pork chops","Meat"],["Bacon","Meat"],["Breakfast sausage","Meat"],["Salmon fillet","Seafood"],["Shrimp","Seafood"],["Tilapia","Seafood"],["Deli turkey","Deli"],["Deli ham","Deli"],["Rotisserie chicken","Deli"],
["Sourdough bread","Bakery"],["Whole wheat bread","Bakery"],["Flour tortillas","Bakery"],["Corn tortillas","Bakery"],["Bagels","Bakery"],["Hamburger buns","Bakery"],["Croissants","Bakery"],
["White rice","Pantry"],["Brown rice","Pantry"],["Spaghetti","Pantry"],["Penne pasta","Pantry"],["Marinara sauce","Pantry"],["Olive oil","Pantry"],["Vegetable oil","Pantry"],["All-purpose flour","Pantry"],["Sugar","Pantry"],["Brown sugar","Pantry"],["Baking soda","Pantry"],["Kosher salt","Pantry"],["Black pepper","Pantry"],["Peanut butter","Pantry"],["Strawberry jam","Pantry"],["Honey","Pantry"],["Oatmeal","Pantry"],["Cheerios","Pantry"],["Granola","Pantry"],["Black beans","Pantry"],["Chickpeas","Pantry"],["Canned tomatoes","Pantry"],["Chicken broth","Pantry"],["Tuna","Pantry"],["Soy sauce","Pantry"],["Sriracha","Pantry"],["Ketchup","Pantry"],["Mayonnaise","Pantry"],["Mustard","Pantry"],["Ranch dressing","Pantry"],["Salsa","Pantry"],["Tortilla chips","Snacks"],["Potato chips","Snacks"],["Pretzels","Snacks"],["Popcorn","Snacks"],["Almonds","Snacks"],["Trail mix","Snacks"],["Protein bars","Snacks"],["Oreos","Snacks"],["Graham crackers","Snacks"],["Dark chocolate","Snacks"],
["Frozen pizza","Frozen"],["Frozen berries","Frozen"],["Frozen broccoli","Frozen"],["Ice cream","Frozen"],["Frozen waffles","Frozen"],["Frozen burritos","Frozen"],["Frozen chicken nuggets","Frozen"],
["Sparkling water","Drinks"],["Bottled water","Drinks"],["Orange juice","Drinks"],["Coffee beans","Drinks"],["Ground coffee","Drinks"],["Cold brew","Drinks"],["Green tea","Drinks"],["Coca-Cola","Drinks"],["Gatorade","Drinks"],["Red Bull","Drinks"],["Kombucha","Drinks"],["Beer 12-pack","Drinks"],["Red wine","Drinks"],
["Paper towels","Household"],["Toilet paper","Household"],["Dish soap","Household"],["Laundry detergent","Household"],["Trash bags","Household"],["Aluminum foil","Household"],["Ziploc bags","Household"],["Sponges","Household"],["Hand soap","Household"],
["Toothpaste","Personal"],["Shampoo","Personal"],["Body wash","Personal"],["Deodorant","Personal"],["Razors","Personal"],["Ibuprofen","Personal"],["Vitamins","Personal"],["Sunscreen","Personal"],
["Dog food","Pets"],["Cat food","Pets"],["Cat litter","Pets"],
["Protein powder","Health"],["Creatine","Health"],["Pre-workout","Health"],["Electrolyte packets","Health"],
];
export const AISLE_ORDER = ["Produce","Bakery","Deli","Meat","Seafood","Dairy","Pantry","Snacks","Frozen","Drinks","Household","Personal","Health","Pets","Other"];
export const QUICK_ADD = ["Bananas","Large eggs","Whole milk","Chicken breast","Avocados","Sourdough bread","Greek yogurt","Paper towels"];
